name: CMake CI

# События, которые запускают workflow
on:
  # При пуше в указанные ветки
  push:
    branches: [dev, main]
  # При создании Pull Request в указанные ветки
  pull_request:
    branches: [dev, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Конфигурация CMake
        run: cmake -S . -B build

      - name: Сборка проекта
        run: cmake --build build

      - name: Запуск тестов
        run: ctest --test-dir build --output-on-failure
